#!/bin/sh

set -e

CAPSTOMP_TARGET="libcapstomp.so"
CAPSTOMP_PATH="/usr/lib/capstomp/$CAPSTOMP_TARGET"

CAPSTOMP_DB_DIRECTORY="/usr/lib64/mariadb/plugins"
if [ -d ${CAPSTOMP_DB_DIRECTORY} ]; then
    ln -vsf ${CAPSTOMP_PATH} "${CAPSTOMP_DB_DIRECTORY}/${CAPSTOMP_TARGET}"
    exit 0
fi

CAPSTOMP_DB_DIRECTORY="/usr/lib64/mysql/plugins"
if [ -d ${CAPSTOMP_DB_DIRECTORY} ]; then
    ln -vsf ${CAPSTOMP_PATH} "${CAPSTOMP_DB_DIRECTORY}/${CAPSTOMP_TARGET}"
fi

exit 0
