#!/bin/sh

set -e

CAPSTOMP_NAME="libcapstomp.so"
CAPSTOMP_PATH="/usr/lib/capstomp/$CAPSTOMP_NAME"

for DB_TYPE in "mariadb" "mysql"
do
    for PLUGIN_DIR in "plugin" "plugins"
    do
        DB_DIRECTORY="/usr/lib/$DB_TYPE/$PLUGIN_DIR"
        if [ -d $DB_DIRECTORY ]; then
            ln -vsf $CAPSTOMP_PATH "$DB_DIRECTORY/$CAPSTOMP_NAME"
        fi
    done
done

exit 0
