#!/bin/sh

set -e

for DB_TYPE in "mariadb" "mysql"
do
    for PLUGIN_DIR in "plugin" "plugins"
    do
        CAPSTOMP_PATH="/usr/lib/$DB_TYPE/$PLUGIN_DIR/libcapstomp.so"
        if [ -L $CAPSTOMP_PATH ]; then
            rm -v $CAPSTOMP_PATH
        exit 0
    done
done

exit 0
