---
name: linux
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build: 
    name: "ubuntu-latest-test-build"
    runs-on: ubuntu-latest
        
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build build-essential
          
      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCAPSTOMP_HAVE_MY_BOOL=OFF \
            -DCAPSTOMP_STATIC_LIBEVENT=ON
          
      - name: Build
        run: |
          cmake --build build --config Release
